/*
 * PitchBook API
 *
 * API for a sports pitch booking mobile application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookingsPostRequest {
    #[serde(rename = "pitchId")]
    pub pitch_id: String,
    #[serde(rename = "slotId")]
    pub slot_id: String,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<PaymentMethod>,
}

impl BookingsPostRequest {
    pub fn new(pitch_id: String, slot_id: String, date: String) -> BookingsPostRequest {
        BookingsPostRequest {
            pitch_id,
            slot_id,
            date,
            payment_method: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentMethod {
    #[serde(rename = "card")]
    Card,
    #[serde(rename = "paypal")]
    Paypal,
}

impl Default for PaymentMethod {
    fn default() -> PaymentMethod {
        Self::Card
    }
}

