/*
 * PitchBook API
 *
 * API for a sports pitch booking mobile application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Booking {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "pitchId", skip_serializing_if = "Option::is_none")]
    pub pitch_id: Option<String>,
    #[serde(rename = "pitchName", skip_serializing_if = "Option::is_none")]
    pub pitch_name: Option<String>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    #[serde(rename = "totalPrice", skip_serializing_if = "Option::is_none")]
    pub total_price: Option<f64>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "sport", skip_serializing_if = "Option::is_none")]
    pub sport: Option<String>,
}

impl Booking {
    pub fn new() -> Booking {
        Booking {
            id: None,
            pitch_id: None,
            pitch_name: None,
            date: None,
            start_time: None,
            end_time: None,
            total_price: None,
            status: None,
            sport: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "upcoming")]
    Upcoming,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Upcoming
    }
}

