/*
 * PitchBook API
 *
 * API for a sports pitch booking mobile application.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;

#[skip_serializing_none]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Pitch {
    pub id: String,
    pub name: String,
    pub sport: String,
    pub location: String,
    pub address: String,
    pub price_per_hour: f64,
    pub rating: f64,
    pub review_count: i32,
    pub image_url: String,
    pub amenities: Vec<String>,
    pub description: String,
    pub owner_name: String,
    pub owner_avatar: String,
}
