/*
 * PitchBook API
 *
 * API for a sports pitch booking mobile application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    #[serde(rename = "memberSince", skip_serializing_if = "Option::is_none")]
    pub member_since: Option<String>,
    #[serde(rename = "totalBookings", skip_serializing_if = "Option::is_none")]
    pub total_bookings: Option<i32>,
    #[serde(rename = "favoriteSport", skip_serializing_if = "Option::is_none")]
    pub favorite_sport: Option<String>,
}

impl User {
    pub fn new() -> User {
        User {
            name: None,
            email: None,
            avatar: None,
            member_since: None,
            total_bookings: None,
            favorite_sport: None,
        }
    }
}

